import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Navigation } from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next JS Demo",
  description: "Generated by create Deniz Gökbudak",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="bg-slate-900 text-white p-4 text-center">
            {/* Welcome to Next.js 15 Crash Course */}
            <Navigation />
          </header>
          {children}
          <footer className="bg-slate-900 text-white p-4 text-center">
            <p>Copyright 2023 Deniz Gökbudak</p>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
